# This is a basic workflow to help you get started with Actions

name: Build-Test

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    env:
      mpsver_major: '2020.1'
      mpsver_minor: '7'

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Start message
        run: echo Starting Build-Release

      # You can get the exact version of the JDK needed from the jbr subdirectory 
      # of your installed MPS. Alternatively, this action could be changed to obtain the 
      # JetBrains-patched JDK (e.g. from Itemis Nexus or somewhere from JetBrains)
      - name: Set up JDK 11.0.7 for x64
        uses: actions/setup-java@v1
        with:
          java-version: '11.0.7'
          architecture: x64

      # Runs a set of commands using the runners shell
      - name: Build
        run: |
          wget https://download-cf.jetbrains.com/mps/MPS-$mpsver_major.$mpsver_minor
          unzip "MPS-$mpsver_major.$mpsver_minor.zip"
          ant -Dmps_home="./MPS\ $mpsver_major clean generate assemble"
          mv "build/artifacts/com.dslfoundry.langvis/com.dslfoundry.langvis.zip" "build/artifacts/com.dslfoundry.langvis/com.dslfoundry.langvis-MPS-$mpsver_major.$mpsver_minor.zip'
      
      - name: Upload
        uses: actions/upload-artifact@v2-preview
        with:
          name: plugin
          path: 'build/artifacts/com.dslfoundry.langvis/com.dslfoundry.langvis-MPS-${{env.mpsver_major}}.${{env.mpsver_minor}}.zip'
          
